/// Flutter icons Socicon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Socicon
///      fonts:
///       - asset: fonts/Socicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Socicon {
  Socicon._();

  static const _kFontFam = 'Socicon';

  static const IconData github = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData googleplus = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData amazon = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData apple = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData itunes = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData quora = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData youtube = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData whatsapp = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData chrome = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData firefox = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData microsoft = const IconData(0xe90e, fontFamily: _kFontFam);
}
